(part "SRU8043-3R9Y"
    (packageRef "SRU80433R9Y")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "SRU8043-3R9Y")
    (property "Mouser_Part_Number" "652-SRU8043-3R9Y")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/SRU8043-3R9Y?qs=3fQS%252B%2FKBkgycpx7rnbhNgQ%3D%3D")
    (property "Arrow_Part_Number" "SRU8043-3R9Y")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sru8043-3r9y/bourns?utm_currency=USD&region=nac")
    (property "Description" "Fixed Inductors 3.9uH 30% SMD 8043")
    (property "Datasheet_Link" "https://www.bourns.com/pdfs/SRU8043.pdf")
    (property "symbolName1" "SRU8043-3R9Y")
)
