(part "IAUCN04S7L028ATMA1"
    (packageRef "IAUC120N06S5N011ATMA1")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_5") (portType INOUT))
        (port "10" (symbPinId 10) (portName "S_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "726-IAUCN04S7L028ATM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/IAUCN04S7L028ATMA1?qs=mELouGlnn3deeHozE86VbA%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IAUCN04S7L028ATMA1")
    (property "Description" "MOSFET MOSFET_(20V 40V)")
    (property "Datasheet_Link" "https://www.infineon.com/dgdl/Infineon-IAUCN04S7L028-DataSheet-v01_00-EN.pdf?fileId=8ac78c8c8d2fe47b018d35eccb611a5a")
    (property "symbolName1" "IAUCN04S7L028ATMA1")
)
